### ISSUE TITLE
这个问题怎么解决

### ISSUE THREAD

**Issue by OrangeKing-King** [0x727/ObserverWard_0x727#3]
![image](https://user-images.githubusercontent.com/56219922/130340485-b7a67777-8b89-4c73-90a7-37aafa07c857.png)

**Comment by cn-kali-team** [comment]
挂代理，或者设置源镜像
https://mirrors.tuna.tsinghua.edu.cn/help/rustup/
https://rsproxy.cn/
随便选一个
