### ISSUE TITLE
mac乱码

### ISSUE THREAD

**Issue by hu185396** [0x727/ObserverWard_0x727#4]
![image](https://user-images.githubusercontent.com/50415778/130759210-dab36d98-8ad1-4479-8c18-5f07f8814939.png)
![image](https://user-images.githubusercontent.com/50415778/130759314-44f32fd8-0f7b-4708-9513-6b0dc4d473d0.png)
如图

**Comment by cn-kali-team** [comment]
我没有Mac系统，那咋办啊

**Comment by cn-kali-team** [comment]
我这没有测试到有乱码哦

**Comment by cn-kali-team** [comment]
要不你更新一下，下载最新的再试试
