### ISSUE TITLE
识别过后的结果没有路径

### ISSUE THREAD

**Issue by hu185396** [0x727/ObserverWard_0x727#6]
识别http://xxxx/test/index.html这种格式，识别过后输出的结果没有路径，网站不支持跳转的话，不方便查看啊
![image](https://user-images.githubusercontent.com/50415778/134756408-cbfe0452-614d-44d2-80ce-239465850505.png)

**Comment by cn-kali-team** [comment]
是留着输入时候的URL还是跟着跳转的URL，之前是留在跳转后的URL的，但是有时候会很长，表格会撑爆不太好看。
下次更新留下输入时的目标URL吧

**Comment by hu185396** [comment]
> 确实太长会影响美观性，但是碰到不少带路径和不带路径是两个站点，批量识别后默认去掉路径还是有些不太方便

**Comment by cn-kali-team** [comment]
> > 确实太长会影响美观性，但是碰到不少带路径和不带路径是两个站点，批量识别后默认去掉路径还是有些不太方便

稍等，这就更新

**Comment by cn-kali-team** [comment]
等着跑完了，全部变绿色就可以重新下载了
https://github.com/0x727/ObserverWard_0x727/actions/runs/1533544080

**Comment by cn-kali-team** [comment]
可以更新下载了
