### ISSUE TITLE
Release建议增加版本号

### ISSUE THREAD

**Issue by Rvn0xsy** [0x727/ObserverWard_0x727#8]
Release版本建议增加版本号，这样可以通过https://api.github.com/repos/0x727/ObserverWard_0x727/tags 直接下载到编译好的二进制文件。

例如：https://github.com/Rvn0xsy/red-tldr/releases
在接口中：https://api.github.com/repos/Rvn0xsy/red-tldr/tags

**Comment by cn-kali-team** [comment]
不是都可以下载吗？我更新比较频繁，不想每次都打tags编译发布，所以固定使用`default`标签了。

**Comment by cn-kali-team** [comment]
- 下载最新版本
```bash
curl -L https://github.com/0x727/ObserverWard_0x727/releases/download/default/observer_ward_amd64 --output observer_ward_amd64
```
- 加速代理
```
https://github.91chifun.workers.dev/https://github.com//0x727/ObserverWard_0x727/releases/download/default/observer_ward_amd64
```
