### ISSUE TITLE
macOS inter版运行报错

### ISSUE THREAD

**Issue by simonlee-hello** [0x727/ObserverWard_0x727#9]
thread 'main' panicked at 'BAD JSON: Error("invalid type: integer `46`, expected a string", line: 34298, column: 26)', what_web/src/fingerprint.rs:164:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    41266 abort      ./observer_ward_darwin

**Comment by cn-kali-team** [comment]
指纹库是-u更新的吗，用编辑器打开看到是完整的吗？

**Comment by Wh0ale** [comment]
Linux kali 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux
使用最新版出现一样的问题。指纹库是-u更新的。

![image](https://user-images.githubusercontent.com/44937351/154420245-0cb2dc01-bc34-4934-bf21-17d7dbc791fa.png)

**Comment by cn-kali-team** [comment]
刚刚添加了一个向日葵的指纹46没转字符串再`-u`更新一下指纹
